import { CaptionSegment, Participant, Session } from '../../types/realtime';

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    participantId: 'p-host-01',
    displayName: 'Elena Rostova',
    deviceId: 'macbook-pro-mic',
    deviceType: 'laptop',
    deviceLabel: 'Host · MacBook Pro Mic',
    joinedAt: Date.now() - 320000,
    lastSeenAt: Date.now(),
    connectionState: 'CONNECTED',
    microphoneState: 'ACTIVE',
    qualityScore: 98,
    isHost: true,
    isLocal: true,
    audioLevel: 0,
    tableAngle: 270, // 6 o'clock
  },
  {
    participantId: 'p-alice-02',
    displayName: 'Alice Zhao',
    deviceId: 'iphone-15-pro',
    deviceType: 'mobile',
    deviceLabel: 'Alice’s iPhone 15 Pro',
    joinedAt: Date.now() - 310000,
    lastSeenAt: Date.now(),
    connectionState: 'CONNECTED',
    microphoneState: 'ACTIVE',
    qualityScore: 94,
    audioLevel: 0,
    tableAngle: 340,
  },
  {
    participantId: 'p-marcus-03',
    displayName: 'Marcus Vance',
    deviceId: 'pixel-8-pro',
    deviceType: 'mobile',
    deviceLabel: 'Marcus’s Pixel 8',
    joinedAt: Date.now() - 290000,
    lastSeenAt: Date.now(),
    connectionState: 'CONNECTED',
    microphoneState: 'ACTIVE',
    qualityScore: 89,
    audioLevel: 0,
    tableAngle: 60,
  },
  {
    participantId: 'p-sofia-04',
    displayName: 'Sofia Lindqvist',
    deviceId: 'ipad-pro-mic',
    deviceType: 'tablet',
    deviceLabel: 'Sofia’s iPad Pro',
    joinedAt: Date.now() - 250000,
    lastSeenAt: Date.now(),
    connectionState: 'CONNECTED',
    microphoneState: 'ACTIVE',
    qualityScore: 92,
    audioLevel: 0,
    tableAngle: 130,
  },
  {
    participantId: 'p-david-05',
    displayName: 'David Kim',
    deviceId: 'galaxy-s24-mic',
    deviceType: 'mobile',
    deviceLabel: 'David’s Galaxy S24',
    joinedAt: Date.now() - 200000,
    lastSeenAt: Date.now(),
    connectionState: 'CONNECTED',
    microphoneState: 'MUTED',
    qualityScore: 86,
    audioLevel: 0,
    tableAngle: 200,
  },
];

export const INITIAL_TRANSCRIPT_SEGMENTS: CaptionSegment[] = [
  {
    segmentId: 'seg-101',
    sessionId: 'session-demo',
    speakerId: 'p-host-01',
    speakerName: 'Elena Rostova',
    sourceDeviceId: 'macbook-pro-mic',
    startMs: 1400,
    endMs: 5200,
    text: 'Good morning everyone. Thanks for placing your phones on the table. We’re testing Roundtable’s distributed acoustic fusion today.',
    status: 'FINAL',
    confidence: 'high',
    overlap: false,
    createdAt: Date.now() - 315000,
    updatedAt: Date.now() - 312000,
    duplicateSourcesCount: 3,
  },
  {
    segmentId: 'seg-102',
    sessionId: 'session-demo',
    speakerId: 'p-alice-02',
    speakerName: 'Alice Zhao',
    sourceDeviceId: 'iphone-15-pro',
    startMs: 6100,
    endMs: 9800,
    text: 'My phone is sitting right next to Marcus. Even with quiet speech, the closest microphone picks up the clearest signal.',
    status: 'FINAL',
    confidence: 'high',
    overlap: false,
    createdAt: Date.now() - 308000,
    updatedAt: Date.now() - 305000,
    duplicateSourcesCount: 4,
  },
  {
    segmentId: 'seg-103',
    sessionId: 'session-demo',
    speakerId: 'p-marcus-03',
    speakerName: 'Marcus Vance',
    sourceDeviceId: 'pixel-8-pro',
    startMs: 10400,
    endMs: 14800,
    text: 'Right. Normally in a room like this, single-mic captioning misses half of what’s said across the table.',
    status: 'FINAL',
    confidence: 'high',
    overlap: false,
    createdAt: Date.now() - 300000,
    updatedAt: Date.now() - 296000,
    duplicateSourcesCount: 2,
  },
  {
    segmentId: 'seg-104',
    sessionId: 'session-demo',
    speakerId: 'p-sofia-04',
    speakerName: 'Sofia Lindqvist',
    sourceDeviceId: 'ipad-pro-mic',
    startMs: 15600,
    endMs: 19400,
    text: 'And when people talk over each other, single mics produce gibberish. Let’s see what happens during simultaneous speech.',
    status: 'FINAL',
    confidence: 'high',
    overlap: false,
    createdAt: Date.now() - 290000,
    updatedAt: Date.now() - 286000,
    duplicateSourcesCount: 3,
  },
  {
    segmentId: 'seg-105-a',
    sessionId: 'session-demo',
    speakerId: 'p-alice-02',
    speakerName: 'Alice Zhao',
    sourceDeviceId: 'iphone-15-pro',
    startMs: 20100,
    endMs: 23400,
    text: 'We should definitely schedule the release for Friday afternoon.',
    status: 'FINAL',
    confidence: 'high',
    overlap: true,
    overlapGroupId: 'overlap-grp-01',
    createdAt: Date.now() - 280000,
    updatedAt: Date.now() - 277000,
    duplicateSourcesCount: 1,
  },
  {
    segmentId: 'seg-105-b',
    sessionId: 'session-demo',
    speakerId: 'p-marcus-03',
    speakerName: 'Marcus Vance',
    sourceDeviceId: 'pixel-8-pro',
    startMs: 20400,
    endMs: 23600,
    text: 'No, Friday releases are dangerous! Monday morning is much safer.',
    status: 'FINAL',
    confidence: 'high',
    overlap: true,
    overlapGroupId: 'overlap-grp-01',
    createdAt: Date.now() - 280000,
    updatedAt: Date.now() - 277000,
    duplicateSourcesCount: 1,
  },
  {
    segmentId: 'seg-106',
    sessionId: 'session-demo',
    speakerId: 'p-host-01',
    speakerName: 'Elena Rostova',
    sourceDeviceId: 'macbook-pro-mic',
    startMs: 24500,
    endMs: 28800,
    text: 'Notice how the system detected simultaneous speech and kept both streams clean and attributed without mixing.',
    status: 'FINAL',
    confidence: 'high',
    overlap: false,
    createdAt: Date.now() - 270000,
    updatedAt: Date.now() - 266000,
    duplicateSourcesCount: 4,
  },
  {
    segmentId: 'seg-107',
    sessionId: 'session-demo',
    speakerId: 'p-sofia-04',
    speakerName: 'Sofia Lindqvist',
    sourceDeviceId: 'ipad-pro-mic',
    startMs: 29500,
    endMs: 33200,
    text: 'The acoustic fusion engine weights the closest device highest and suppresses echo from other phones.',
    status: 'UPDATED',
    confidence: 'high',
    overlap: false,
    createdAt: Date.now() - 25000,
    updatedAt: Date.now() - 12000,
    duplicateSourcesCount: 3,
  },
  {
    segmentId: 'seg-108',
    sessionId: 'session-demo',
    speakerId: 'p-alice-02',
    speakerName: 'Alice Zhao',
    sourceDeviceId: 'iphone-15-pro',
    startMs: 34100,
    endMs: 37800,
    text: 'Testing live streaming words as speech arrives...',
    status: 'PROVISIONAL',
    confidence: 'medium',
    overlap: false,
    createdAt: Date.now() - 5000,
    updatedAt: Date.now() - 1000,
    duplicateSourcesCount: 2,
  },
];

export function createInitialSession(roomName = 'Weekly Product & Architecture Sync', hostName = 'Elena Rostova'): Session {
  const joinCode = '7F2K9';
  const participants = [...INITIAL_PARTICIPANTS];
  participants[0] = {
    ...participants[0],
    displayName: hostName,
  };

  return {
    sessionId: 'sess-demo-7f2k9',
    joinCode,
    name: roomName,
    createdAt: Date.now() - 320000,
    startedAt: Date.now() - 315000,
    status: 'LIVE',
    participants,
    transcriptSegments: [...INITIAL_TRANSCRIPT_SEGMENTS],
    metrics: {
      medianLatencyMs: 780,
      p95LatencyMs: 1320,
      speechEvents: 42,
      correctionCount: 9,
      overlapCount: 4,
      deduplicatedEvents: 31,
      connectedDevices: 5,
      audioChunkLatencyMs: 140,
      asrLatencyMs: 460,
      fusionLatencyMs: 180,
    },
  };
}

export interface ConversationTurnScenario {
  speakerId: string;
  speakerName: string;
  sourceDeviceId: string;
  provisionalSteps: string[];
  finalText: string;
  isOverlap?: boolean;
  overlapPartner?: {
    speakerId: string;
    speakerName: string;
    sourceDeviceId: string;
    text: string;
  };
  durationMs: number;
}

export const LIVE_SIMULATION_SCRIPT: ConversationTurnScenario[] = [
  {
    speakerId: 'p-marcus-03',
    speakerName: 'Marcus Vance',
    sourceDeviceId: 'pixel-8-pro',
    provisionalSteps: [
      'The audio worklet is',
      'The audio worklet is downsampling to 16kHz',
      'The audio worklet is downsampling to 16kHz PCM chunks cleanly.',
    ],
    finalText: 'The audio worklet is downsampling to 16 kHz PCM chunks cleanly on all devices.',
    durationMs: 4000,
  },
  {
    speakerId: 'p-sofia-04',
    speakerName: 'Sofia Lindqvist',
    sourceDeviceId: 'ipad-pro-mic',
    provisionalSteps: [
      'That means low memory',
      'That means low memory overhead even during',
      'That means low memory overhead even during long two-hour lectures.',
    ],
    finalText: 'That means low memory overhead even during long two-hour lectures and team meetings.',
    durationMs: 3800,
  },
  {
    speakerId: 'p-alice-02',
    speakerName: 'Alice Zhao',
    sourceDeviceId: 'iphone-15-pro',
    provisionalSteps: [
      'I can see the room code',
      'I can see the room code clearly on my phone screen',
      'I can see the room code clearly on my phone screen, latency is under 800ms.',
    ],
    finalText: 'I can see the room code clearly on my phone screen, latency is consistently under 800ms.',
    isOverlap: true,
    overlapPartner: {
      speakerId: 'p-host-01',
      speakerName: 'Elena Rostova',
      sourceDeviceId: 'macbook-pro-mic',
      text: 'And notice that the provisional caption gets updated in-place without duplicating.',
    },
    durationMs: 4500,
  },
  {
    speakerId: 'p-david-05',
    speakerName: 'David Kim',
    sourceDeviceId: 'galaxy-s24-mic',
    provisionalSteps: [
      'Unmuting from the other side',
      'Unmuting from the other side of the table now.',
    ],
    finalText: 'Unmuting from the other side of the table now. The acoustic confidence stays high!',
    durationMs: 3500,
  },
  {
    speakerId: 'p-host-01',
    speakerName: 'Elena Rostova',
    sourceDeviceId: 'macbook-pro-mic',
    provisionalSteps: [
      'Let us review the evaluation',
      'Let us review the evaluation screen to compare with single mic.',
    ],
    finalText: 'Let’s review the evaluation screen to see the direct comparison against a single microphone baseline.',
    durationMs: 3600,
  },
];
